### ISSUE TITLE
黑名單修改，form欄位不對

### ISSUE THREAD

**Issue by chicheng567** [luluchiu82/public-space-borrow#4]
![Screenshot from 2024-03-23 01-19-35](https://github.com/luluchiu82/public-space-borrow/assets/83914075/02c55e68-771e-4f3d-a3a9-e76f4a58ea2f)
封鎖原因跟解鎖日期對調後，修改沒有對調，會造成無法修改

**Comment by Yun-Pei** [comment]
已糾正，另外增加「建立日期」的欄位
